### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [arnabsen1729/arnabsen1729#2]
[Click Here](https://github.com/Jaidevstudio/support/issues/new/choose)

**Comment by arnabsen1729** [comment]
@VasudevJaiswal can I get some context?

**Comment by VasudevJaiswal** [comment]
https://github.com/Jaidevstudio

**Comment by VasudevJaiswal** [comment]
Check your email or org page

**Comment by VasudevJaiswal** [comment]
### 🎉🎊Welcome to **Jaidev Studio**🎉🎊!!

- **Why not contribute to...**
-  [Unique-Github-Profiles](https://github.com/Jaidevstudio/Unique-Github-Profiles)!

**Comment by VasudevJaiswal** [comment]
#Dear Member
You show that you are part of this org, by making your org badge public. This will show our profile org on your profile to others:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)
